// auto-generated by abis; created on 2026-09-21T19:45:45-04:00
package abis_test

import (
	"math"
	"github.com/I-Am-Dench/abis"
)

func (c Custom) AppendBinary(buf []byte) ([]byte, error) {
	var err error
	if buf, err = c.Environment.AppendBinary(buf); err != nil {
		return buf, err
	}
	return buf, nil
}

func (c *Custom) AdvanceBinary(data []byte) ([]byte, error) {
	var err error
	if data, err = c.Environment.AdvanceBinary(data); err != nil {
		return data, abis.NewAdvanceError("Environment", err)
	}
	return data, nil
}

func (e Embedded) AppendBinary(buf []byte) ([]byte, error) {
	buf = abis.AppendString(buf, e.Name)
	buf = abis.AppendUint64(buf, math.Float64bits(e.Currency))
	return buf, nil
}

func (e *Embedded) AdvanceBinary(data []byte) ([]byte, error) {
	var err error
	if data, err = abis.AdvanceString(data, &e.Name); err != nil {
		return data, abis.NewAdvanceError("Name", nil)
	}
	if data, err = abis.AdvanceFloat64(data, &e.Currency); err != nil {
		return data, abis.NewAdvanceError("Currency", nil)
	}
	return data, nil
}

func (i Indicies) AppendBinary(buf []byte) ([]byte, error) {
	buf = abis.AppendUint64(buf, uint64(i.Lower))
	buf = abis.AppendUint64(buf, uint64(i.Upper))
	return buf, nil
}

func (i *Indicies) AdvanceBinary(data []byte) ([]byte, error) {
	var err error
	if data, err = abis.AdvanceInt(data, &i.Lower); err != nil {
		return data, abis.NewAdvanceError("Lower", nil)
	}
	if data, err = abis.AdvanceInt(data, &i.Upper); err != nil {
		return data, abis.NewAdvanceError("Upper", nil)
	}
	return data, nil
}

func (p Packet) AppendBinary(buf []byte) ([]byte, error) {
	var err error
	if buf, err = p.Embedded.AppendBinary(buf); err != nil {
		return buf, err
	}
	buf = abis.AppendBool(buf, p.Flag)
	buf = abis.AppendUint64(buf, uint64(p.Foo))
	buf = abis.AppendUint8(buf, uint8(p.Char))
	buf = abis.AppendUint16(buf, uint16(p.Short))
	buf = abis.AppendUint32(buf, uint32(p.Index))
	buf = abis.AppendUint64(buf, uint64(p.Long))
	buf = abis.AppendUint64(buf, uint64(p.Unsigned))
	buf = abis.AppendUint8(buf, p.Byte)
	buf = abis.AppendUint16(buf, p.Word)
	buf = abis.AppendUint32(buf, p.BigNumber)
	buf = abis.AppendUint64(buf, p.Address)
	buf = abis.AppendUint32(buf, math.Float32bits(p.Rate))
	buf = abis.AppendUint64(buf, math.Float64bits(p.Factor))
	buf = abis.AppendString(buf, p.Text)
	if buf, err = p.Indicies.AppendBinary(buf); err != nil {
		return buf, err
	}
	if buf, err = p.Environment.AppendBinary(buf); err != nil {
		return buf, err
	}
	if buf, err = abis.AppendArray(buf, p.Points); err != nil {
		return buf, err
	}
	return buf, nil
}

func (p *Packet) AdvanceBinary(data []byte) ([]byte, error) {
	var err error
	if data, err = p.Embedded.AdvanceBinary(data); err != nil {
		return data, abis.NewAdvanceError("Embedded", err)
	}
	if data, err = abis.AdvanceBool(data, &p.Flag); err != nil {
		return data, abis.NewAdvanceError("Flag", nil)
	}
	if data, err = abis.AdvanceInt(data, &p.Foo); err != nil {
		return data, abis.NewAdvanceError("Foo", nil)
	}
	if data, err = abis.AdvanceInt8(data, &p.Char); err != nil {
		return data, abis.NewAdvanceError("Char", nil)
	}
	if data, err = abis.AdvanceInt16(data, &p.Short); err != nil {
		return data, abis.NewAdvanceError("Short", nil)
	}
	if data, err = abis.AdvanceInt32(data, &p.Index); err != nil {
		return data, abis.NewAdvanceError("Index", nil)
	}
	if data, err = abis.AdvanceInt64(data, &p.Long); err != nil {
		return data, abis.NewAdvanceError("Long", nil)
	}
	if data, err = abis.AdvanceUint(data, &p.Unsigned); err != nil {
		return data, abis.NewAdvanceError("Unsigned", nil)
	}
	if data, err = abis.AdvanceUint8(data, &p.Byte); err != nil {
		return data, abis.NewAdvanceError("Byte", nil)
	}
	if data, err = abis.AdvanceUint16(data, &p.Word); err != nil {
		return data, abis.NewAdvanceError("Word", nil)
	}
	if data, err = abis.AdvanceUint32(data, &p.BigNumber); err != nil {
		return data, abis.NewAdvanceError("BigNumber", nil)
	}
	if data, err = abis.AdvanceUint64(data, &p.Address); err != nil {
		return data, abis.NewAdvanceError("Address", nil)
	}
	if data, err = abis.AdvanceFloat32(data, &p.Rate); err != nil {
		return data, abis.NewAdvanceError("Rate", nil)
	}
	if data, err = abis.AdvanceFloat64(data, &p.Factor); err != nil {
		return data, abis.NewAdvanceError("Factor", nil)
	}
	if data, err = abis.AdvanceString(data, &p.Text); err != nil {
		return data, abis.NewAdvanceError("Text", nil)
	}
	if data, err = p.Indicies.AdvanceBinary(data); err != nil {
		return data, abis.NewAdvanceError("Indicies", err)
	}
	if data, err = p.Environment.AdvanceBinary(data); err != nil {
		return data, abis.NewAdvanceError("Environment", err)
	}
	if data, err = abis.AdvanceArray(data, &p.Points); err != nil {
		return data, abis.NewAdvanceError("Points", err)
	}
	return data, nil
}

func (v Vector) AppendBinary(buf []byte) ([]byte, error) {
	buf = abis.AppendUint64(buf, math.Float64bits(v.X))
	buf = abis.AppendUint64(buf, math.Float64bits(v.Y))
	return buf, nil
}

func (v *Vector) AdvanceBinary(data []byte) ([]byte, error) {
	var err error
	if data, err = abis.AdvanceFloat64(data, &v.X); err != nil {
		return data, abis.NewAdvanceError("X", nil)
	}
	if data, err = abis.AdvanceFloat64(data, &v.Y); err != nil {
		return data, abis.NewAdvanceError("Y", nil)
	}
	return data, nil
}

func (w *WithAdvancer) AdvanceBinary(data []byte) ([]byte, error) {
	return data, nil
}

func (w WithAppender) AppendBinary(buf []byte) ([]byte, error) {
	return buf, nil
}
